#ifndef FLUTTER_PLUGIN_VPN_PLUGIN_H_
#define FLUTTER_PLUGIN_VPN_PLUGIN_H_

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include <flutter/event_channel.h>
#include <flutter/plugin_registrar_windows.h>
#include <flutter/standard_method_codec.h>

#include <memory>
#include <mutex>
#include <optional>
#include <string>
#include <vector>

// Pigeon-generated bindings — defines vpn_plugin namespace with IVpnManager,
// IDeepLink, VpnManagerState, FlutterError, ErrorOr, etc.
#include "runner/platform_api.g.h"

namespace vpn_plugin {

// ── Enums not generated by pigeon ─────────────────────────────────────────────

enum class VpnProtocol : int64_t { kQuic = 0, kHttp2 = 1 };
enum class RoutingMode  : int64_t { kVpn  = 0, kBypass = 1 };

enum class AddNewServerResult : int64_t {
  kOk                 = 0,
  kIpAddressIncorrect = 1,
  kDomainIncorrect    = 2,
  kUsernameIncorrect  = 3,
  kPasswordIncorrect  = 4,
  kDnsServersIncorrect = 5,
};

// ── Data structures ───────────────────────────────────────────────────────────

struct Server {
  int64_t id;
  std::string ip_address;
  std::string domain;
  std::string login;
  std::string password;
  std::vector<std::string> dns_servers;
  VpnProtocol vpn_protocol;
  int64_t routing_profile_id;
};

struct RoutingProfile {
  int64_t id;
  std::string name;
  RoutingMode default_mode;
  std::vector<std::string> bypass_rules;
  std::vector<std::string> vpn_rules;
};

struct VpnRequest {
  std::string zoned_date_time;
  std::string protocol_name;
  RoutingMode decision;
  std::string source_ip_address;
  std::string destination_ip_address;
  std::string source_port;
  std::string destination_port;
  std::string domain;
};

// WM_USER message used to marshal VPN state changes onto the UI thread.
// WPARAM carries the VpnManagerState integer value.
static constexpr UINT WM_VPN_STATE = WM_USER + 1;

// ── Storage ───────────────────────────────────────────────────────────────────

class WindowsStorage {
 public:
  WindowsStorage();

  std::vector<Server>&           AllServers()              { return servers_; }
  std::vector<RoutingProfile>&   AllRoutingProfiles()      { return routing_profiles_; }
  std::optional<int64_t>&        CurrentSelectedServerId() { return selected_server_id_; }
  std::string&                   CurrentExcludedRoutes()   { return excluded_routes_; }
  VpnManagerState&               CurrentVpnState()         { return vpn_state_; }
  std::vector<VpnRequest>&       AllRequests()             { return requests_; }

 private:
  void InitDefaultData();

  std::vector<Server>          servers_;
  std::vector<RoutingProfile>  routing_profiles_;
  std::optional<int64_t>       selected_server_id_;
  std::string                  excluded_routes_;
  VpnManagerState              vpn_state_ = VpnManagerState::kDisconnected;
  std::vector<VpnRequest>      requests_;
};

// ── Event stream handler ──────────────────────────────────────────────────────

class VpnEventStreamHandler
    : public flutter::StreamHandler<flutter::EncodableValue> {
 public:
  explicit VpnEventStreamHandler(WindowsStorage* storage);

  // Called on the UI thread only (via WM_VPN_STATE message dispatch).
  void EmitState(VpnManagerState state);

 protected:
  std::unique_ptr<flutter::StreamHandlerError<flutter::EncodableValue>>
  OnListenInternal(const flutter::EncodableValue* arguments,
                   std::unique_ptr<flutter::EventSink<flutter::EncodableValue>>&& events) override;

  std::unique_ptr<flutter::StreamHandlerError<flutter::EncodableValue>>
  OnCancelInternal(const flutter::EncodableValue* arguments) override;

 private:
  WindowsStorage*                                                     storage_;
  std::mutex                                                       mutex_;
  std::unique_ptr<flutter::EventSink<flutter::EncodableValue>>     sink_;
};

// ── VPN manager — bridges to vpn_easy.dll ────────────────────────────────────

class IVpnManagerImpl : public IVpnManager {
 public:
  IVpnManagerImpl(WindowsStorage* storage, VpnEventStreamHandler* handler, HWND msg_hwnd);
  ~IVpnManagerImpl() override;

  // IVpnManager overrides.
  std::optional<FlutterError> Start(const std::string& server_name,
                                    const std::string& config) override;
  std::optional<FlutterError> Stop() override;
  std::optional<FlutterError> UpdateConfiguration(const std::string* server_name,
                                                  const std::string* config) override;
  ErrorOr<VpnManagerState> GetCurrentState() override;
  std::optional<FlutterError> SetDebugLogging(bool enabled) override;

 private:
  // Called from the vpn_easy state-change callback (arbitrary thread).
  // Posts WM_VPN_STATE to msg_hwnd_ to marshal onto the UI thread.
  static void OnVpnStateChanged(void* arg, int new_state);

  WindowsStorage*           storage_;
  VpnEventStreamHandler* handler_;
  HWND                   msg_hwnd_;
};

// ── Deep link stub (required by pigeon registration) ─────────────────────────

class IDeepLinkImpl : public IDeepLink {
 public:
  ErrorOr<std::string> Decode(const std::string& /*uri*/) override {
    return std::string{};
  }
};

// ── Storage / server / routing managers ──────────────────────────────────────

class StorageManagerImpl {
 public:
  explicit StorageManagerImpl(WindowsStorage* storage) : storage_(storage) {}
  void SetExcludedRoutes(const std::string& routes)               { storage_->CurrentExcludedRoutes() = routes; }
  void SetRoutingProfiles(const std::vector<RoutingProfile>& p)   { storage_->AllRoutingProfiles() = p; }
  void SetSelectedServerId(int64_t id)                            { storage_->CurrentSelectedServerId() = id; }
  void SetServers(const std::vector<Server>& servers)             { storage_->AllServers() = servers; }
  std::vector<VpnRequest>      GetAllRequests()       { return storage_->AllRequests(); }
  std::string                  GetExcludedRoutes()    { return storage_->CurrentExcludedRoutes(); }
  std::vector<RoutingProfile>  GetRoutingProfiles()   { return storage_->AllRoutingProfiles(); }
  std::optional<int64_t>       GetSelectedServerId()  { return storage_->CurrentSelectedServerId(); }
  std::vector<Server>          GetAllServers()        { return storage_->AllServers(); }

 private:
  WindowsStorage* storage_;
};

class ServersManagerImpl {
 public:
  explicit ServersManagerImpl(WindowsStorage* storage) : storage_(storage) {}
  AddNewServerResult AddNewServer(const std::string& name, const std::string& ip,
                                  const std::string& domain, const std::string& user,
                                  const std::string& pass, VpnProtocol proto,
                                  int64_t routing_profile_id, const std::string& dns_csv);
  std::vector<Server> GetAllServers() { return storage_->AllServers(); }
  AddNewServerResult SetNewServer(int64_t id, const std::string& name, const std::string& ip,
                                  const std::string& domain, const std::string& user,
                                  const std::string& pass, VpnProtocol proto,
                                  int64_t routing_profile_id, const std::string& dns_csv);
  void SetSelectedServerId(int64_t id) { storage_->CurrentSelectedServerId() = id; }
  void RemoveServer(int64_t id);

  static bool                      IsValidIp(const std::string& ip);
  static std::vector<std::string>  SplitAndTrim(const std::string& s, char delim);
  static void                      Trim(std::string& s);

 private:
  WindowsStorage* storage_;
};

class RoutingProfilesManagerImpl {
 public:
  explicit RoutingProfilesManagerImpl(WindowsStorage* storage) : storage_(storage) {}
  void                        AddNewProfile();
  std::vector<RoutingProfile> GetAllProfiles() { return storage_->AllRoutingProfiles(); }
  void SetDefaultRoutingMode(int64_t id, RoutingMode mode);
  void SetProfileName(int64_t id, const std::string& name);
  void SetRules(int64_t id, RoutingMode mode, const std::string& rules);
  void RemoveAllRules(int64_t id);

 private:
  WindowsStorage* storage_;
};

// ── Plugin ────────────────────────────────────────────────────────────────────

class VpnPlugin : public flutter::Plugin {
 public:
  static void RegisterWithRegistrar(flutter::PluginRegistrarWindows* registrar);

  explicit VpnPlugin(
      HWND msg_hwnd,
      std::unique_ptr<flutter::EventChannel<flutter::EncodableValue>> event_channel,
      std::shared_ptr<WindowsStorage>                   storage,
      std::unique_ptr<IVpnManagerImpl>               vpn_manager,
      std::unique_ptr<StorageManagerImpl>            storage_manager,
      std::unique_ptr<ServersManagerImpl>            servers_manager,
      std::unique_ptr<RoutingProfilesManagerImpl>    routing_manager);

  ~VpnPlugin() override;

  VpnPlugin(const VpnPlugin&)             = delete;
  VpnPlugin& operator=(const VpnPlugin&)  = delete;

 private:
  HWND                                                            msg_hwnd_;
  std::unique_ptr<flutter::EventChannel<flutter::EncodableValue>> event_channel_;
  std::shared_ptr<WindowsStorage>                    storage_;
  std::unique_ptr<IVpnManagerImpl>                vpn_manager_;
  std::unique_ptr<StorageManagerImpl>             storage_manager_;
  std::unique_ptr<ServersManagerImpl>             servers_manager_;
  std::unique_ptr<RoutingProfilesManagerImpl>     routing_manager_;
};

}  // namespace vpn_plugin

#endif  // FLUTTER_PLUGIN_VPN_PLUGIN_H_
